import { useState, useEffect, useRef, useCallback } from "react";

// ─── DATA ───────────────────────────────────────────────────────────────────

const TEAM_NAMES = [
  "404: Sleep Not Found", "NullPointer Exception Handlers", "Stack Overflow Survivors",
  "Ctrl+Alt+Defeat", "The Git Pushers", "Bug Whisperers", "RAM Raiders",
  "The Merge Conflicts", "Undefined Behaviour", "The Infinite Loopers",
  "Segfault Samurai", "The Recursion Rangers", "localhost Legends",
  "The Cache Money Crew", "sudo rm -rf Life", "The Async Avengers",
  "Divide By Zero Heroes", "The Off-By-One Gang", "The Binary Bros",
  "Semicolon Slayers",
];

const TAGLINES = [
  "We build what shouldn't exist.",
  "Shipping bugs since day one.",
  "Our code works on our machine.",
  "Making the impossible unnecessarily complicated.",
  "Breaking prod, one feature at a time.",
  "We Google harder than anyone.",
  "Chaos is just agile development.",
  "The error is not in our code. It's in reality.",
  "We don't have bugs, we have features.",
  "Debugging life, one panic at a time.",
];

const TECHS = ["AI-powered", "Blockchain-enabled", "IoT-connected", "AR-enhanced",
  "Quantum-charged", "ML-driven", "Web3-integrated", "5G-turbo", "Cloud-native",
  "Edge-computing", "NFT-backed", "Metaverse-ready", "Cybersecurity-hardened", "API-fueled"];

const OBJECTS = ["Dustbin", "Fan", "Refrigerator", "Toothbrush", "Pillow",
  "Parking Lot", "Atta Chakki", "Broom", "Chair", "Mirror", "Ceiling Fan",
  "Water Bottle", "Pressure Cooker", "Notebook", "AutoRickshaw", "Almirah",
  "Mosquito Bat", "Cooler", "Tubelight", "Dhobi Ghat"];

const TWISTS = ["with anger issues", "that's emotionally unstable", "but for introverts",
  "that ghosted its developer", "with existential dread", "but make it dramatic",
  "powered by chai and regret", "that cries in JavaScript", "with trust issues",
  "but it's also a startup", "that learned from TikTok", "with 3 PhDs and no job",
  "that's on its main character arc", "but it's also unionized", "that went to IIT but still failed"];

const ROASTS = [
  "Bhai, this is either genius or the worst idea since Java 😭",
  "Your idea is so bad it completed a full circle and became brilliant 🤌",
  "The judges haven't left the room yet. That's already a win. 💀",
  "Bold move. No one has done this before. Mostly because they had sense. 😂",
  "This prompt was generated by chaos and seasoned with delusion. Perfect. 🔥",
  "I've seen better ideas on a Monday morning with no coffee. Still, go for it. ☕",
  "The confidence you'll need to present this is frankly inspiring. 😎",
  "Your future CTO is somewhere watching this and cringing already. 📈",
];

const HYPE_MESSAGES = [
  "Judges are watching 👀",
  "Confidence > Logic 😎",
  "Fake it till you win 💀",
  "Your startup is already valued at ₹2Cr 💸",
  "The demo WILL crash. Act surprised. 🎭",
  "Everyone else is scared. Be terrifying. 👹",
  "Code less. Vibe more. ✨",
  "Sleep is for people without PRs 😤",
  "You are built different. Like, really different. 🧠",
  "The bug is not a bug. It's a feature demo. 🐛",
  "Ship it. Ship it. SHIP IT. 🚀",
  "Your README will save you 📖",
];

const RULES = [
  { icon: "⏱", title: "Time Limit", desc: "35 minutes to build from scratch. No extensions. No mercy. The clock doesn't care about your feelings." },
  { icon: "🎲", title: "Stick to Your Prompt", desc: "Your chaos prompt is your idea. No swapping, no ignoring it. You asked for chaos, you got it." },
  { icon: "👥", title: "Team Size", desc: "Solo or team — maximum 4 members. Every member must contribute. Spectators are not teammates." },
  { icon: "🚫", title: "No Pre-Built Code", desc: "No copy-pasting your old projects. Build fresh. We're watching. Probably." },
  { icon: "🎯", title: "Demo Required", desc: "You must present a working demo — or at least a convincing fake one. Confidence is a feature. 💀" },
  { icon: "🏆", title: "Judging Criteria", desc: "Creativity, execution, chaos energy, and how well you sell it. Vibes absolutely matter here." },
  { icon: "📦", title: "Submission", desc: "Submit your GitHub link or a working URL before the timer hits zero. Late = disqualified." },
  { icon: "☕", title: "Chai Policy", desc: "Unlimited chai. Mandatory. Non-negotiable. Fuel yourself appropriately." },
];

// ─── GLOBAL STYLES ────────────────────────────────────────────────────────────

const GLOBAL_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #050010; }
  input { outline: none; }
  ::-webkit-scrollbar { width: 4px; background: #0a0020; }
  ::-webkit-scrollbar-thumb { background: #8338ec; border-radius: 99px; }

  .neon-btn {
    cursor: pointer; border: none; border-radius: 14px;
    font-family: 'Bebas Neue', cursive; letter-spacing: 2px;
    transition: all 0.25s ease;
  }
  .neon-btn:hover { transform: translateY(-3px) scale(1.02); filter: brightness(1.15); }
  .neon-btn:active { transform: scale(0.97); }

  .ghost-btn {
    cursor: pointer; background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.15); color: #fff;
    border-radius: 10px; font-family: 'Space Mono', monospace;
    font-size: 12px; padding: 10px 18px; transition: all 0.2s;
  }
  .ghost-btn:hover { background: rgba(255,255,255,0.1); transform: translateY(-1px); }

  .glass-card {
    background: rgba(255,255,255,0.04);
    backdrop-filter: blur(20px);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 24px;
  }

  .pill-name {
    display: flex; align-items: center; gap: 8px;
    background: rgba(131,56,236,0.2); border: 1px solid #8338ec55;
    border-radius: 99px; padding: 6px 14px;
    font-size: 14px; color: #fff; font-family: 'Space Mono', monospace;
  }
  .pill-name button {
    background: none; border: none; color: #ff006e;
    cursor: pointer; font-size: 16px; line-height: 1;
  }

  .team-edit-input {
    background: transparent; border: none;
    border-bottom: 2px solid rgba(6,214,160,0.3);
    color: #fff; font-family: 'Bebas Neue', cursive;
    letter-spacing: 2px; text-align: center; width: 100%;
    padding: 4px 8px; transition: border-color 0.2s ease;
  }
  .team-edit-input:focus { outline: none; border-bottom-color: #06d6a0; }
  .team-edit-input::placeholder { color: #ffffff33; }

  .team-tagline-input {
    background: transparent; border: none;
    border-bottom: 2px solid rgba(6,214,160,0.15);
    color: #06d6a0; font-family: 'Space Mono', monospace;
    text-align: center; width: 100%; max-width: 480px;
    padding: 4px 8px; transition: border-color 0.2s ease;
  }
  .team-tagline-input:focus { outline: none; border-bottom-color: #06d6a066; }

  .rule-card {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 16px; padding: 20px;
    transition: all 0.2s ease;
  }
  .rule-card:hover {
    background: rgba(131,56,236,0.08);
    border-color: rgba(131,56,236,0.3);
    transform: translateY(-2px);
  }

  @keyframes float { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-10px); } }
  @keyframes fadeUp { from { opacity:0; transform:translateY(24px); } to { opacity:1; transform:translateY(0); } }
  @keyframes glow {
    0%,100% { filter: drop-shadow(0 0 16px #8338eccc) drop-shadow(0 0 32px #ff006e66); }
    50% { filter: drop-shadow(0 0 28px #3a86ffcc) drop-shadow(0 0 56px #8338ec88); }
  }
  @keyframes ticker { from { transform: translateX(0); } to { transform: translateX(-50%); } }
  @keyframes promptReveal { from { opacity:0; transform:scale(0.9) translateY(16px); } to { opacity:1; transform:scale(1) translateY(0); } }
  @keyframes roastSlide { from { opacity:0; transform:translateX(-20px); } to { opacity:1; transform:translateX(0); } }
  @keyframes blink { 0%,100% { opacity:1; } 50% { opacity:0.3; } }
  @keyframes urgentPulse { from { box-shadow: 0 0 20px #ff006e66; } to { box-shadow: 0 0 60px #ff006ebb; } }
  @keyframes lockShake {
    0%,100% { transform: translateX(0); }
    20% { transform: translateX(-6px); }
    40% { transform: translateX(6px); }
    60% { transform: translateX(-4px); }
    80% { transform: translateX(4px); }
  }

  .glitch-wrap { position: relative; display: inline-block; }
  .glitch-wrap::before, .glitch-wrap::after {
    content: attr(data-text); position: absolute; top: 0; left: 0;
    width: 100%; height: 100%; pointer-events: none;
    background: inherit; -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  }
  .glitch-wrap::before {
    animation: glitch1 3s infinite;
    clip-path: polygon(0 30%, 100% 30%, 100% 50%, 0 50%);
    filter: drop-shadow(-3px 0 #ff006e);
  }
  .glitch-wrap::after {
    animation: glitch2 3s infinite;
    clip-path: polygon(0 60%, 100% 60%, 100% 80%, 0 80%);
    filter: drop-shadow(3px 0 #3a86ff);
  }
  @keyframes glitch1 {
    0%,94%,100% { transform:translateX(0); opacity:0; }
    95% { transform:translateX(-4px); opacity:0.9; }
    97% { transform:translateX(4px); opacity:0.9; }
  }
  @keyframes glitch2 {
    0%,96%,100% { transform:translateX(0); opacity:0; }
    97% { transform:translateX(4px); opacity:0.9; }
    99% { transform:translateX(-2px); opacity:0.9; }
  }
`;

// ─── CONFETTI ────────────────────────────────────────────────────────────────

function Confetti({ active }) {
  const canvasRef = useRef(null);
  const animRef = useRef(null);
  useEffect(() => {
    if (!active) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    const colors = ["#ff006e","#fb5607","#ffbe0b","#3a86ff","#8338ec","#06d6a0","#ff4d6d"];
    let list = Array.from({ length: 120 }, () => ({
      x: Math.random() * canvas.width, y: -20,
      r: Math.random() * 8 + 4,
      color: colors[Math.floor(Math.random() * colors.length)],
      vx: (Math.random() - 0.5) * 6, vy: Math.random() * 4 + 2,
      rot: Math.random() * 360, rotV: (Math.random() - 0.5) * 8,
      shape: Math.random() > 0.5 ? "rect" : "circle",
    }));
    let frame = 0;
    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      list.forEach(p => {
        ctx.save(); ctx.translate(p.x, p.y); ctx.rotate((p.rot * Math.PI) / 180);
        ctx.fillStyle = p.color;
        if (p.shape === "rect") ctx.fillRect(-p.r, -p.r / 2, p.r * 2, p.r);
        else { ctx.beginPath(); ctx.arc(0, 0, p.r, 0, Math.PI * 2); ctx.fill(); }
        ctx.restore();
        p.x += p.vx; p.y += p.vy; p.rot += p.rotV; p.vy += 0.05;
      });
      list = list.filter(p => p.y < canvas.height + 20);
      frame++;
      if (list.length > 0 && frame < 300) animRef.current = requestAnimationFrame(animate);
      else ctx.clearRect(0, 0, canvas.width, canvas.height);
    };
    animRef.current = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(animRef.current);
  }, [active]);
  return <canvas ref={canvasRef} style={{ position:"fixed", top:0, left:0, pointerEvents:"none", zIndex:9999 }} />;
}

// ─── GLITCH TEXT ─────────────────────────────────────────────────────────────

function GlitchText({ text, gradient }) {
  return (
    <span
      className="glitch-wrap"
      data-text={text}
      style={{
        position:"relative", display:"inline-block",
        background: gradient, WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent",
      }}
    >
      {text}
    </span>
  );
}

// ─── COUNTDOWN ───────────────────────────────────────────────────────────────

function Countdown({ seconds, onDone }) {
  const [left, setLeft] = useState(seconds);
  useEffect(() => {
    if (left <= 0) { onDone?.(); return; }
    const t = setInterval(() => setLeft(l => l - 1), 1000);
    return () => clearInterval(t);
  }, [left]);
  const m = String(Math.floor(left / 60)).padStart(2, "0");
  const s = String(left % 60).padStart(2, "0");
  const pct = (left / seconds) * 100;
  const urgent = left <= 300;
  return (
    <div style={{
      background:"rgba(0,0,0,0.6)", backdropFilter:"blur(12px)",
      border:`2px solid ${urgent ? "#ff006e" : "#ffbe0b"}`,
      borderRadius:20, padding:"28px 40px", textAlign:"center",
      boxShadow:`0 0 40px ${urgent ? "#ff006e66" : "#ffbe0b44"}`,
      animation: urgent ? "urgentPulse 0.8s ease-in-out infinite alternate" : "none",
    }}>
      <div style={{ fontSize:13, fontFamily:"'Space Mono',monospace", color: urgent ? "#ff006e" : "#ffbe0b", letterSpacing:4, marginBottom:8 }}>
        {urgent ? "⚠ TIME RUNNING OUT" : "⏱ BUILD TIME REMAINING"}
      </div>
      <div style={{ fontSize:72, fontFamily:"'Space Mono',monospace", fontWeight:700, color: urgent ? "#ff006e" : "#fff", lineHeight:1, letterSpacing:-2 }}>
        {m}:{s}
      </div>
      <div style={{ marginTop:12, height:6, background:"#ffffff22", borderRadius:99, overflow:"hidden" }}>
        <div style={{
          width:`${pct}%`, height:"100%", borderRadius:99,
          background: urgent ? "linear-gradient(90deg,#ff006e,#ff4d6d)" : "linear-gradient(90deg,#ffbe0b,#06d6a0)",
          transition:"width 1s linear",
        }} />
      </div>
    </div>
  );
}

// ─── HYPE MODE ───────────────────────────────────────────────────────────────

function HypeOverlay({ onClose }) {
  const [msgIdx, setMsgIdx] = useState(0);
  const [fade, setFade] = useState(true);
  useEffect(() => {
    const t = setInterval(() => {
      setFade(false);
      setTimeout(() => { setMsgIdx(i => (i + 1) % HYPE_MESSAGES.length); setFade(true); }, 300);
    }, 1800);
    return () => clearInterval(t);
  }, []);
  return (
    <div onClick={onClose} style={{ position:"fixed", inset:0, zIndex:1000, background:"radial-gradient(ellipse at center, #1a0040 0%, #000 100%)", display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", cursor:"pointer", overflow:"hidden" }}>
      {[...Array(6)].map((_,i) => (
        <div key={i} style={{ position:"absolute", width:300+i*80, height:300+i*80, borderRadius:"50%", background:["#ff006e","#8338ec","#3a86ff","#fb5607","#06d6a0","#ffbe0b"][i], opacity:0.15, top:`${[10,60,30,70,20,50][i]}%`, left:`${[20,70,50,10,80,40][i]}%`, transform:"translate(-50%,-50%)", filter:"blur(60px)", animation:`blobPulse${i} ${2+i*0.5}s ease-in-out infinite alternate` }} />
      ))}
      <style>{[...Array(6)].map((_,i)=>`@keyframes blobPulse${i}{from{transform:translate(-50%,-50%) scale(1)}to{transform:translate(-50%,-50%) scale(1.3)}}`).join("")}</style>
      <div style={{ position:"relative", textAlign:"center", padding:"0 24px" }}>
        <div style={{ fontSize:13, fontFamily:"'Space Mono',monospace", color:"#ffffff88", letterSpacing:6, marginBottom:32 }}>🔥 HYPE MODE ACTIVATED 🔥</div>
        <div style={{ fontSize:"clamp(28px,7vw,72px)", fontFamily:"'Bebas Neue',cursive", letterSpacing:2, lineHeight:1.1, color:"#fff", opacity: fade ? 1 : 0, transition:"opacity 0.3s ease", textShadow:"0 0 40px #ff006e, 0 0 80px #8338ec", maxWidth:700 }}>
          {HYPE_MESSAGES[msgIdx]}
        </div>
        <div style={{ marginTop:40, fontSize:13, color:"#ffffff44", fontFamily:"'Space Mono',monospace" }}>tap anywhere to exit</div>
      </div>
    </div>
  );
}

// ─── MAIN APP ─────────────────────────────────────────────────────────────────

const HERO_GRADIENT = "linear-gradient(135deg, #ffffff 0%, #e0aaff 20%, #ff006e 55%, #ffbe0b 100%)";

export default function BuildChella() {
  const [names, setNames] = useState([]);
  const [nameInput, setNameInput] = useState("");
  const [started, setStarted] = useState(false);

  const [team, setTeam] = useState(null);
  const [customName, setCustomName] = useState("");
  const [customTagline, setCustomTagline] = useState("");

  const [prompt, setPrompt] = useState(null);
  const [promptParts, setPromptParts] = useState(null);
  const [roast, setRoast] = useState(null);
  const [promptKey, setPromptKey] = useState(0);
  const [promptLocked, setPromptLocked] = useState(false);
  const [shakeLocked, setShakeLocked] = useState(false);

  const [timerActive, setTimerActive] = useState(false);
  const [timerKey, setTimerKey] = useState(0);
  const [timerDone, setTimerDone] = useState(false);

  const [hypeMode, setHypeMode] = useState(false);
  const [confettiKey, setConfettiKey] = useState(0);
  const [confettiActive, setConfettiActive] = useState(false);

  const fireConfetti = useCallback(() => {
    setConfettiKey(k => k + 1);
    setConfettiActive(true);
    setTimeout(() => setConfettiActive(false), 50);
  }, []);

  const pick = arr => arr[Math.floor(Math.random() * arr.length)];

  const handleAddName = () => {
    const n = nameInput.trim();
    if (n && !names.includes(n)) { setNames(ns => [...ns, n]); setNameInput(""); }
  };

  const handleStart = () => {
    const pending = nameInput.trim();
    const all = pending ? [...names, pending] : [...names];
    if (all.length === 0) return;
    setNames(all);
    setNameInput("");
    setStarted(true);
    fireConfetti();
  };

  const generateTeam = () => {
    const n = pick(TEAM_NAMES);
    const t = pick(TAGLINES);
    setTeam({ name: n, tagline: t });
    setCustomName(n);
    setCustomTagline(t);
    fireConfetti();
  };

  const generatePrompt = () => {
    if (promptLocked) {
      setShakeLocked(true);
      setTimeout(() => setShakeLocked(false), 600);
      return;
    }
    const tech = pick(TECHS);
    const obj = pick(OBJECTS);
    const twist = pick(TWISTS);
    setPrompt(`${tech} ${obj} ${twist}`);
    setPromptParts({ tech, obj, twist });
    setRoast(pick(ROASTS));
    setPromptKey(k => k + 1);
    setPromptLocked(true);
    setTimerActive(true);
    setTimerKey(k => k + 1);
    setTimerDone(false);
    fireConfetti();
  };

  const displayNames = names.filter(Boolean);
  const isTeam = displayNames.length > 1;

  // ─── Entry Screen ─────────────────────────────────────────────────────────
  if (!started) {
    return (
      <div style={{ minHeight:"100vh", background:"#050010", display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"'Syne',sans-serif", padding:"24px", position:"relative", overflow:"hidden" }}>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Syne:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
        <style>{GLOBAL_STYLES}</style>

        {[{c:"#8338ec",t:"8%",l:"12%",s:420},{c:"#ff006e",t:"62%",l:"72%",s:320},{c:"#3a86ff",t:"78%",l:"18%",s:260}].map((b,i)=>(
          <div key={i} style={{ position:"absolute", width:b.s, height:b.s, borderRadius:"50%", background:b.c, opacity:0.13, top:b.t, left:b.l, filter:"blur(80px)", animation:`float ${4+i}s ease-in-out infinite`, pointerEvents:"none" }} />
        ))}

        <div style={{ position:"relative", width:"100%", maxWidth:520, animation:"fadeUp 0.6s ease" }}>
          <div style={{ textAlign:"center", marginBottom:40 }}>
            <div style={{ fontSize:52, marginBottom:10 }}>🚀</div>
            {/* FIX 1 — Entry screen title: bright white-first gradient + strong glow */}
            <div style={{
              fontFamily:"'Bebas Neue',cursive",
              fontSize:"clamp(52px,13vw,84px)", letterSpacing:5, lineHeight:0.9,
              background: HERO_GRADIENT,
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent",
              filter:"drop-shadow(0 0 18px #8338ecbb) drop-shadow(0 0 36px #ff006e55)",
            }}>
              BUILD-CHELLA
            </div>
            <div style={{ fontSize:12, color:"#ffffff55", fontFamily:"'Space Mono',monospace", letterSpacing:4, marginTop:12 }}>BY ZENCODERS</div>
          </div>

          <div className="glass-card" style={{ padding:"36px" }}>
            <div style={{ fontSize:13, color:"#ffffff66", fontFamily:"'Space Mono',monospace", marginBottom:20, letterSpacing:2 }}>WHO'S BUILDING TODAY?</div>

            <div style={{ display:"flex", flexWrap:"wrap", gap:8, marginBottom:16, minHeight:36 }}>
              {displayNames.map((n,i) => (
                <div key={i} className="pill-name">
                  <span>{n}</span>
                  <button onClick={() => setNames(ns => ns.filter((_,j)=>j!==i))}>×</button>
                </div>
              ))}
            </div>

            <div style={{ display:"flex", gap:10 }}>
              <input
                value={nameInput}
                onChange={e => setNameInput(e.target.value)}
                onKeyDown={e => e.key === "Enter" && handleAddName()}
                placeholder={displayNames.length === 0 ? "Your name..." : "Add teammate..."}
                style={{ flex:1, background:"rgba(255,255,255,0.07)", border:"1px solid rgba(255,255,255,0.15)", borderRadius:12, padding:"14px 18px", color:"#fff", fontSize:15, fontFamily:"'Syne',sans-serif" }}
              />
              <button className="ghost-btn" onClick={handleAddName}>+ Add</button>
            </div>

            {displayNames.length > 0 && (
              <div style={{ marginTop:10, fontSize:12, color:"#ffffff44", fontFamily:"'Space Mono',monospace" }}>
                {displayNames.length === 1 ? "Solo builder detected 🧑‍💻" : `Team of ${displayNames.length} detected 🤝`}
              </div>
            )}

            <button
              className="neon-btn"
              onClick={handleStart}
              style={{
                marginTop:28, width:"100%", padding:"18px 0",
                background:"linear-gradient(135deg,#8338ec,#ff006e)",
                color:"#fff", fontSize:22, boxShadow:"0 0 30px #8338ec66",
                opacity: (displayNames.length === 0 && !nameInput.trim()) ? 0.4 : 1,
              }}
            >
              LET'S BUILD 🔥
            </button>
          </div>
        </div>

        <Confetti key={confettiKey} active={confettiActive} />
      </div>
    );
  }

  // ─── Main Page ────────────────────────────────────────────────────────────
  return (
    <div style={{ minHeight:"100vh", background:"#050010", fontFamily:"'Syne',sans-serif", color:"#fff", overflowX:"hidden" }}>
      <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Syne:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
      <style>{GLOBAL_STYLES}</style>

      {/* Ambient blobs */}
      <div style={{ position:"fixed", inset:0, pointerEvents:"none", zIndex:0 }}>
        {[{c:"#8338ec",t:"5%",l:"10%",s:500,d:0},{c:"#ff006e",t:"50%",l:"75%",s:400,d:1},{c:"#3a86ff",t:"80%",l:"15%",s:350,d:2},{c:"#fb5607",t:"25%",l:"55%",s:300,d:3}].map((b,i)=>(
          <div key={i} style={{ position:"absolute", width:b.s, height:b.s, borderRadius:"50%", background:b.c, opacity:0.09, top:b.t, left:b.l, filter:"blur(90px)", animation:`float ${5+b.d}s ease-in-out infinite`, animationDelay:`${b.d*0.7}s` }} />
        ))}
      </div>

      {/* Ticker */}
      <div style={{ position:"sticky", top:0, zIndex:100, overflow:"hidden", background:"rgba(131,56,236,0.92)", backdropFilter:"blur(10px)", borderBottom:"1px solid #8338ec55", padding:"10px 0" }}>
        <div style={{ display:"flex", whiteSpace:"nowrap", animation:"ticker 20s linear infinite" }}>
          {[...Array(2)].map((_,k)=>(
            <span key={k} style={{ display:"flex" }}>
              {["🚀 BUILD-CHELLA 2025","🔥 ZENCODERS","💡 HACK THE PLANET","🎸 BUILD SOMETHING WILD","👾 35 MINS ON THE CLOCK","⚡ COFFEE & CODE","🎯 SHIP OR DIE","🏆 ONE WINNER, MANY REGRETS"].map((t,i)=>(
                <span key={i} style={{ padding:"0 32px", fontSize:13, fontFamily:"'Space Mono',monospace", letterSpacing:3, color:"#fff" }}>{t}</span>
              ))}
            </span>
          ))}
        </div>
      </div>

      <div style={{ position:"relative", zIndex:1, maxWidth:900, margin:"0 auto", padding:"0 20px 80px" }}>

        {/* ── HERO ── */}
        <section style={{ textAlign:"center", padding:"80px 0 60px", animation:"fadeUp 0.8s ease" }}>
          <div style={{ display:"inline-flex", alignItems:"center", background:"rgba(255,190,11,0.15)", border:"1px solid #ffbe0b44", borderRadius:99, padding:"6px 20px", marginBottom:28 }}>
            <span style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffbe0b", letterSpacing:3 }}>ORGANIZED BY ZENCODERS</span>
          </div>

          {/* FIX 1 — Main hero: white-first gradient, strong glow, bigger size */}
          <h1 style={{
            fontFamily:"'Bebas Neue',cursive",
            fontSize:"clamp(76px,18vw,152px)", lineHeight:0.88, letterSpacing:5,
            display:"block", marginBottom:8,
            animation:"glow 4s ease-in-out infinite",
          }}>
            <GlitchText text="BUILD-CHELLA" gradient={HERO_GRADIENT} />
          </h1>

          <div style={{ fontSize:"clamp(18px,4vw,34px)", color:"#8338ec", letterSpacing:6, marginBottom:14 }}>🚀</div>
          <p style={{ fontSize:"clamp(15px,2.5vw,20px)", color:"#ffffffaa", maxWidth:500, margin:"0 auto 12px", lineHeight:1.6 }}>
            Turn useless ideas into something meaningful
          </p>

          <div style={{ display:"flex", alignItems:"center", justifyContent:"center", gap:8, flexWrap:"wrap", marginBottom:44 }}>
            {isTeam ? (
              <>
                <span style={{ fontSize:13, color:"#ffffff44", fontFamily:"'Space Mono',monospace" }}>TEAM:</span>
                {displayNames.map((n,i)=>(
                  <span key={i} style={{ background:"rgba(131,56,236,0.25)", border:"1px solid #8338ec55", borderRadius:99, padding:"4px 14px", fontSize:13, fontFamily:"'Space Mono',monospace", color:"#c77dff" }}>{n}</span>
                ))}
              </>
            ) : (
              <span style={{ background:"rgba(58,134,255,0.2)", border:"1px solid #3a86ff55", borderRadius:99, padding:"6px 20px", fontSize:14, fontFamily:"'Space Mono',monospace", color:"#74b9ff" }}>
                👤 {displayNames[0]}
              </span>
            )}
          </div>

          <button className="neon-btn" onClick={generateTeam} style={{ padding:"20px 52px", fontSize:23, background:"linear-gradient(135deg,#8338ec,#ff006e,#ffbe0b)", color:"#fff", boxShadow:"0 0 40px #8338ec88, 0 0 80px #ff006e44" }}>
            Start Building ✨
          </button>
        </section>

        {/* ── TEAM GENERATOR ── */}
        <section style={{ marginBottom:32, animation:"fadeUp 0.8s ease 0.1s both" }}>
          <div className="glass-card" style={{ padding:"36px", textAlign:"center" }}>
            <div style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffffff44", letterSpacing:4, marginBottom:20 }}>▸ TEAM GENERATOR</div>

            <button className="neon-btn" onClick={generateTeam} style={{ padding:"16px 36px", fontSize:18, background:"linear-gradient(135deg,#06d6a0,#3a86ff)", color:"#000", marginBottom: team ? 28 : 0, boxShadow:"0 0 24px #06d6a044" }}>
              🎲 Generate Team Name
            </button>

            {/* FIX 2 — Editable name & tagline inline */}
            {team && (
              <div style={{ animation:"promptReveal 0.5s ease" }}>
                <div style={{ marginBottom:10, padding:"0 12px" }}>
                  <input
                    className="team-edit-input"
                    value={customName}
                    onChange={e => setCustomName(e.target.value)}
                    placeholder="Your team name..."
                    style={{ fontSize:"clamp(24px,5vw,46px)" }}
                  />
                </div>
                <div style={{ padding:"0 12px" }}>
                  <input
                    className="team-tagline-input"
                    value={customTagline}
                    onChange={e => setCustomTagline(e.target.value)}
                    placeholder="Your tagline..."
                    style={{ fontSize:15 }}
                  />
                </div>
                <div style={{ marginTop:12, fontSize:11, color:"#ffffff33", fontFamily:"'Space Mono',monospace", letterSpacing:1.5 }}>
                  ✏ CLICK EITHER FIELD TO EDIT
                </div>
              </div>
            )}
          </div>
        </section>

        {/* ── PROMPT GENERATOR ── */}
        <section style={{ marginBottom:32, animation:"fadeUp 0.8s ease 0.2s both" }}>
          <div className="glass-card" style={{ padding:"40px", textAlign:"center" }}>
            <div style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffffff44", letterSpacing:4, marginBottom:8 }}>▸ CHAOS PROMPT GENERATOR</div>
            <p style={{ fontSize:14, color:"#ffffff55", marginBottom:28 }}>
              {promptLocked
                ? "🔒 Your prompt is locked in. No take-backs. Build it."
                : "One shot. One prompt. The chaos decides your fate."}
            </p>

            {/* FIX 3 — Locked after first generate */}
            <button
              className="neon-btn"
              onClick={generatePrompt}
              style={{
                padding:"20px 44px", fontSize:22,
                background: promptLocked ? "rgba(60,60,80,0.8)" : "linear-gradient(135deg,#ff006e,#fb5607,#ffbe0b)",
                color: promptLocked ? "#ffffff55" : "#fff",
                border: promptLocked ? "1px solid rgba(255,255,255,0.1)" : "none",
                marginBottom: prompt ? 36 : 0,
                boxShadow: promptLocked ? "none" : "0 0 40px #ff006e55",
                cursor: promptLocked ? "not-allowed" : "pointer",
                animation: shakeLocked ? "lockShake 0.6s ease" : "none",
              }}
            >
              {promptLocked ? "🔒 Prompt Locked — Now Go Build!" : "Generate Your Chaos Prompt 🎲"}
            </button>

            {prompt && (
              <div key={promptKey} style={{ animation:"promptReveal 0.6s cubic-bezier(0.34,1.56,0.64,1)" }}>
                <div style={{ background:"linear-gradient(135deg,rgba(255,0,110,0.1),rgba(131,56,236,0.1))", border:"1px solid rgba(255,0,110,0.35)", borderRadius:18, padding:"32px 24px", marginBottom:20 }}>
                  <div style={{ display:"flex", alignItems:"center", justifyContent:"center", gap:10, marginBottom:14 }}>
                    <div style={{ fontSize:11, fontFamily:"'Space Mono',monospace", color:"#ff006e", letterSpacing:4 }}>YOUR BUILD PROMPT</div>
                    <div style={{ background:"#ff006e22", border:"1px solid #ff006e55", borderRadius:99, padding:"2px 10px", fontSize:10, fontFamily:"'Space Mono',monospace", color:"#ff006e" }}>LOCKED 🔒</div>
                  </div>
                  <div style={{ fontFamily:"'Bebas Neue',cursive", fontSize:"clamp(22px,5vw,44px)", letterSpacing:2, color:"#fff", lineHeight:1.2, textShadow:"0 0 30px #ff006e" }}>
                    {prompt}
                  </div>
                </div>

                <div style={{ display:"flex", flexWrap:"wrap", justifyContent:"center", gap:8, marginBottom:20 }}>
                  {promptParts && [
                    { label: promptParts.tech, tag: "TECH", color: "#3a86ff" },
                    { label: promptParts.obj, tag: "OBJECT", color: "#06d6a0" },
                    { label: promptParts.twist, tag: "TWIST", color: "#ffbe0b" },
                  ].map((t,i)=>(
                    <div key={i} style={{ background:`${t.color}22`, border:`1px solid ${t.color}55`, borderRadius:99, padding:"6px 16px", fontSize:12, fontFamily:"'Space Mono',monospace", color:t.color }}>
                      <span style={{ opacity:0.6 }}>{t.tag}: </span>{t.label}
                    </div>
                  ))}
                </div>

                {roast && (
                  <div style={{ animation:"roastSlide 0.5s ease", background:"rgba(255,190,11,0.08)", border:"1px solid #ffbe0b33", borderRadius:14, padding:"16px 20px", fontSize:14, color:"#ffbe0b", fontFamily:"'Space Mono',monospace", textAlign:"left" }}>
                    💀 <span style={{ opacity:0.7 }}>Honest review:</span> {roast}
                  </div>
                )}
              </div>
            )}
          </div>
        </section>

        {/* ── COUNTDOWN — FIX 4: 35 mins = 2100s ── */}
        {timerActive && (
          <section style={{ marginBottom:32, animation:"fadeUp 0.6s ease" }}>
            <div style={{ textAlign:"center" }}>
              <div style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffffff44", letterSpacing:4, marginBottom:20 }}>▸ COUNTDOWN TO GLORY</div>
              {!timerDone ? (
                <Countdown key={timerKey} seconds={2100} onDone={() => setTimerDone(true)} />
              ) : (
                <div style={{ background:"rgba(255,0,110,0.15)", border:"2px solid #ff006e", borderRadius:20, padding:"32px", animation:"fadeUp 0.5s ease" }}>
                  <div style={{ fontFamily:"'Bebas Neue',cursive", fontSize:48, color:"#ff006e", animation:"blink 1s infinite" }}>⏰ TIME'S UP!</div>
                  <div style={{ fontSize:14, color:"#ffffff66", fontFamily:"'Space Mono',monospace", marginTop:8 }}>Hope you shipped something. Anything. Please.</div>
                  <button className="neon-btn" onClick={() => { setTimerKey(k=>k+1); setTimerDone(false); fireConfetti(); }} style={{ marginTop:20, padding:"12px 28px", fontSize:16, background:"#ff006e", color:"#fff" }}>
                    Reset Timer 🔄
                  </button>
                </div>
              )}
            </div>
          </section>
        )}

        {/* ── HYPE MODE ── */}
        <section style={{ textAlign:"center", marginBottom:32, animation:"fadeUp 0.8s ease 0.3s both" }}>
          <div className="glass-card" style={{ padding:"40px" }}>
            <div style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffffff44", letterSpacing:4, marginBottom:16 }}>▸ EMERGENCY MOTIVATION</div>
            <p style={{ fontSize:15, color:"#ffffff55", marginBottom:28 }}>Confidence dropping? Logic failing? We got you.</p>
            <button
              className="neon-btn"
              onClick={() => { setHypeMode(true); fireConfetti(); }}
              style={{ padding:"22px 52px", fontSize:24, background:"linear-gradient(135deg,#ffbe0b,#fb5607)", color:"#000", letterSpacing:2, boxShadow:"0 0 50px #ffbe0b66, 0 0 100px #fb560733", animation:"float 3s ease-in-out infinite" }}
            >
              Enter Hype Mode 🔥
            </button>
          </div>
        </section>

        {/* ── FIX 5: RULES SECTION ── */}
        <section style={{ marginBottom:48, animation:"fadeUp 0.8s ease 0.4s both" }}>
          <div className="glass-card" style={{ padding:"40px" }}>
            <div style={{ textAlign:"center", marginBottom:36 }}>
              <div style={{ fontSize:12, fontFamily:"'Space Mono',monospace", color:"#ffffff44", letterSpacing:4, marginBottom:14 }}>▸ THE LAW OF THE LAND</div>
              <div style={{ fontFamily:"'Bebas Neue',cursive", fontSize:"clamp(30px,6vw,52px)", letterSpacing:3, color:"#fff" }}>
                Build-Chella Rules 📜
              </div>
              <p style={{ fontSize:13, color:"#ffffff44", fontFamily:"'Space Mono',monospace", marginTop:10 }}>
                Break these and face the judges. They're already judging.
              </p>
            </div>

            <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill, minmax(280px, 1fr))", gap:14 }}>
              {RULES.map((rule, i) => (
                <div key={i} className="rule-card">
                  <div style={{ display:"flex", alignItems:"flex-start", gap:14 }}>
                    <div style={{ fontSize:26, lineHeight:1, flexShrink:0, marginTop:2 }}>{rule.icon}</div>
                    <div>
                      <div style={{ fontFamily:"'Bebas Neue',cursive", fontSize:19, letterSpacing:1.5, color:"#fff", marginBottom:5 }}>{rule.title}</div>
                      <div style={{ fontSize:13, color:"#ffffffaa", lineHeight:1.65, fontFamily:"'Syne',sans-serif" }}>{rule.desc}</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div style={{ marginTop:28, textAlign:"center", padding:"16px 24px", background:"rgba(255,0,110,0.07)", border:"1px solid #ff006e2a", borderRadius:14 }}>
              <span style={{ fontSize:13, fontFamily:"'Space Mono',monospace", color:"#ff006ecc" }}>
                ⚠ The organizers reserve the right to add chaotic rules mid-event. Stay alert.
              </span>
            </div>
          </div>
        </section>

        {/* ── FIX 6: Footer ── */}
        <div style={{ textAlign:"center", paddingTop:32, borderTop:"1px solid rgba(255,255,255,0.06)" }}>
          <div style={{ fontFamily:"'Bebas Neue',cursive", fontSize:22, letterSpacing:4, color:"#ffffff33", marginBottom:14 }}>
            ZENCODERS × BUILD-CHELLA 2025
          </div>
          <div style={{
            display:"inline-block", padding:"10px 28px",
            background:"rgba(255,255,255,0.04)", border:"1px solid rgba(255,255,255,0.1)",
            borderRadius:99, marginBottom:12,
          }}>
            <span style={{
              fontFamily:"'Space Mono',monospace", fontSize:13, fontWeight:700,
              background:"linear-gradient(135deg,#8338ec,#ff006e,#ffbe0b)",
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent",
              letterSpacing:0.5,
            }}>
              ⚡ Developed by the OG Team of Zencoders
            </span>
          </div>
          <div style={{ fontSize:11, color:"#ffffff22", fontFamily:"'Space Mono',monospace" }}>
            made with chaos, chai, and zero sleep
          </div>
        </div>

      </div>

      {hypeMode && <HypeOverlay onClose={() => setHypeMode(false)} />}
      <Confetti key={confettiKey} active={confettiActive} />
    </div>
  );
}
